"""Add APIKey model

Revision ID: ca0c0d7872d7
Revises: 78db466cd25e
Create Date: 2026-06-19 20:10:13.303701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca0c0d7872d7'
down_revision: Union[str, None] = '78db466cd25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_prefix', sa.Text(), nullable=False))
    op.add_column('api_keys', sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.drop_constraint(op.f('api_keys_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_user_id_fkey'), 'api_keys', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'scopes')
    op.drop_column('api_keys', 'key_prefix')
    # ### end Alembic commands ###
